errorbar:
  jshead: [js/d3.v3.js, js/errorbar.js, js/d3-grid.js]
  cdn:
    jshead: 
      - "http://d3js.org/d3.v3.min.js"
      - "http://timelyportfolio.github.io/rCharts_errorbar/js/d3-grid.js"
      - "http://timelyportfolio.github.io/rCharts_errorbar/js/errorbar.js"
